Repository sg8541/minikosa, pull requests merged in 2024-11, with the labels that each got.

#78 feat: Login, Signup API 구현
  frontend/src/main.js
  src/main/java/com/kosa/mini/api/controller/member/LoginApiController.java
  src/main/java/com/kosa/mini/api/controller/member/SignupApiController.java
  src/main/java/com/kosa/mini/api/domain/member/UserSessionDTO.java
  src/main/java/com/kosa/mini/api/exception/DuplicateEmailException.java
  src/main/java/com/kosa/mini/api/exception/DuplicateNicknameException.java
  src/main/java/com/kosa/mini/api/exception/GlobalExceptionHandler.java
  src/main/java/com/kosa/mini/api/exception/LoginException.java
  src/main/java/com/kosa/mini/api/exception/SignupException.java
  src/main/java/com/kosa/mini/api/repository/MemberRepository.java
  src/main/java/com/kosa/mini/api/repository/RoleRepository.java
  src/main/java/com/kosa/mini/api/service/member/LoginService.java
  src/main/java/com/kosa/mini/api/service/member/LoginServiceImpl.java
  src/main/java/com/kosa/mini/api/service/member/SignUpService.java
  src/main/java/com/kosa/mini/api/service/member/SignUpServiceImpl.java
  src/main/java/com/kosa/mini/mvc/controller/member/LoginController.java
  src/main/java/com/kosa/mini/mvc/controller/member/SignupController.java
  src/main/java/com/kosa/mini/mvc/exception/GlobalExceptionHandler.java
  src/main/java/com/kosa/mini/mvc/service/member/LoginService.java
  src/main/java/com/kosa/mini/mvc/service/member/LoginServiceImpl.java
  src/main/java/com/kosa/mini/mvc/service/member/SignUpService.java
  src/main/java/com/kosa/mini/mvc/service/member/SignUpServiceImpl.java
Labels: enhancement

#80 feat: Spring Security, JWT access refresh
  build.gradle
  src/main/java/com/kosa/mini/api/controller/member/LoginApiController.java
  src/main/java/com/kosa/mini/api/controller/member/SignupApiController.java
  src/main/java/com/kosa/mini/api/domain/home/StoreDTO.java
  src/main/java/com/kosa/mini/api/domain/member/ContactUs.java
  src/main/java/com/kosa/mini/api/domain/member/MemberDTO.java
  src/main/java/com/kosa/mini/api/domain/member/TokenResponseDTO.java
  src/main/java/com/kosa/mini/api/domain/member/UserSessionDTO.java
  src/main/java/com/kosa/mini/api/domain/store/StoreContentDTO.java
  src/main/java/com/kosa/mini/api/domain/store/StoreDTO.java
  src/main/java/com/kosa/mini/api/entity/Category.java
  src/main/java/com/kosa/mini/api/entity/Member.java
  src/main/java/com/kosa/mini/api/entity/Menu.java
  src/main/java/com/kosa/mini/api/entity/RefreshToken.java
  src/main/java/com/kosa/mini/api/entity/Review.java
  src/main/java/com/kosa/mini/api/entity/Role.java
  src/main/java/com/kosa/mini/api/entity/Store.java
  src/main/java/com/kosa/mini/api/exception/GlobalExceptionHandler.java
  src/main/java/com/kosa/mini/api/exception/LoginException.java
  src/main/java/com/kosa/mini/api/exception/SignupException.java
  src/main/java/com/kosa/mini/api/repository/MemberRepository.java
  src/main/java/com/kosa/mini/api/repository/RefreshTokenRepository.java
  src/main/java/com/kosa/mini/api/repository/RoleRepository.java
  src/main/java/com/kosa/mini/api/security/DataSourceConfig.java
  src/main/java/com/kosa/mini/api/security/JwtAuthenticationFilter.java
  src/main/java/com/kosa/mini/api/security/JwtTokenProvider.java
  src/main/java/com/kosa/mini/api/security/SecurityConfig.java
  src/main/java/com/kosa/mini/api/security/WebConfig.java
  src/main/java/com/kosa/mini/api/service/member/CustomUserDetailsService.java
  src/main/java/com/kosa/mini/api/service/member/LoginService.java
  src/main/java/com/kosa/mini/api/service/member/LoginServiceImpl.java
  src/main/java/com/kosa/mini/api/service/member/SignUpServiceImpl.java
  src/main/resources/application.properties
Labels: enhancement

#82 hotfix: 댓글 insert 중 에러 발생
  src/main/java/com/kosa/mini/api/controller/member/LoginApiController.java
  src/main/java/com/kosa/mini/api/controller/menu/MenuApiController.java
  src/main/java/com/kosa/mini/api/controller/review/ReviewApiController.java
  src/main/java/com/kosa/mini/api/controller/store/StoreContentApiController.java
  src/main/java/com/kosa/mini/api/dto/review/ReviewReplyDTO.java
  src/main/java/com/kosa/mini/api/dto/review/ReviewResponseDTO.java
  src/main/java/com/kosa/mini/api/dto/review/ReviewSaveDTO.java
  src/main/java/com/kosa/mini/api/dto/review/StoreReviewDTO.java
  src/main/java/com/kosa/mini/api/dto/store/ReplyDTO.java
  src/main/java/com/kosa/mini/api/dto/store/StoreReviewDTO.java
  src/main/java/com/kosa/mini/api/entity/Member.java
  src/main/java/com/kosa/mini/api/entity/Menu.java
  src/main/java/com/kosa/mini/api/entity/RefreshToken.java
  src/main/java/com/kosa/mini/api/entity/Review.java
  src/main/java/com/kosa/mini/api/entity/Store.java
  src/main/java/com/kosa/mini/api/exception/GlobalExceptionHandler.java
  src/main/java/com/kosa/mini/api/exception/LoginException.java
  src/main/java/com/kosa/mini/api/exception/MemberNotFoundException.java
  src/main/java/com/kosa/mini/api/exception/StoreNotFoundException.java
  src/main/java/com/kosa/mini/api/repository/MemberRepository.java
  src/main/java/com/kosa/mini/api/repository/ReviewRepository.java
  src/main/java/com/kosa/mini/api/repository/StoreRepository.java
  src/main/java/com/kosa/mini/api/security/JwtAuthenticationFilter.java
  src/main/java/com/kosa/mini/api/security/JwtTokenProvider.java
  src/main/java/com/kosa/mini/api/security/SecurityConfig.java
  src/main/java/com/kosa/mini/api/service/member/CustomUserDetailsService.java
  src/main/java/com/kosa/mini/api/service/member/LoginService.java
  src/main/java/com/kosa/mini/api/service/member/LoginServiceImpl.java
  src/main/java/com/kosa/mini/api/service/menu/MenuApiServiceImpl.java
  src/main/java/com/kosa/mini/api/service/review/ReviewApiService.java
  src/main/java/com/kosa/mini/api/service/review/ReviewApiServiceImpl.java
  src/main/java/com/kosa/mini/api/service/store/StoreApiService.java
  src/main/java/com/kosa/mini/api/service/store/StoreApiServiceImpl.java
Labels: help wanted, good first issue

#83 fix: 회원 조회 insert 중 에러 발생 임시해결
  src/main/java/com/kosa/mini/api/controller/member/SuggestionApiController.java
  src/main/java/com/kosa/mini/api/dto/member/ContactUs.java
  src/main/java/com/kosa/mini/api/dto/member/ContactUsDTO.java
  src/main/java/com/kosa/mini/api/dto/member/SuggestionDTO.java
  src/main/java/com/kosa/mini/api/entity/ContactUs.java
  src/main/java/com/kosa/mini/api/entity/Member.java
  src/main/java/com/kosa/mini/api/repository/SuggestionRepository.java
  src/main/java/com/kosa/mini/api/service/member/SuggestionServiceImplApi.java
Labels: enhancement

#85 feat: 관리자 기능 추가(게시글, 검색, 가게), 회원 찾기 기능 추가
  src/main/java/com/kosa/mini/api/controller/admin/AdminApiController.java
  src/main/java/com/kosa/mini/api/controller/member/FindApiController.java
  src/main/java/com/kosa/mini/api/controller/member/SuggestionApiController.java
  src/main/java/com/kosa/mini/api/dto/member/EmailFindRequest.java
  src/main/java/com/kosa/mini/api/dto/member/EmailFindResponse.java
  src/main/java/com/kosa/mini/api/dto/member/PasswordResetRequest.java
  src/main/java/com/kosa/mini/api/dto/member/PasswordResetResponse.java
  src/main/java/com/kosa/mini/api/dto/member/UserSearchDTO.java
  src/main/java/com/kosa/mini/api/dto/request/AssignOwnerRequest.java
  src/main/java/com/kosa/mini/api/dto/request/StoreExistenceRequest.java
  src/main/java/com/kosa/mini/api/dto/request/UserExistenceRequest.java
  src/main/java/com/kosa/mini/api/dto/response/ApiError.java
  src/main/java/com/kosa/mini/api/dto/response/AssignOwnerResponse.java
  src/main/java/com/kosa/mini/api/dto/response/ExistenceResponse.java
  src/main/java/com/kosa/mini/api/dto/store/Store.java
  src/main/java/com/kosa/mini/api/dto/store/StoreSearchDTO.java
  src/main/java/com/kosa/mini/api/exception/GlobalExceptionHandler.java
  src/main/java/com/kosa/mini/api/exception/InvalidPasswordResetException.java
  src/main/java/com/kosa/mini/api/exception/PasswordMismatchException.java
  src/main/java/com/kosa/mini/api/exception/ResourceNotFoundException.java
  src/main/java/com/kosa/mini/api/repository/MemberRepository.java
  src/main/java/com/kosa/mini/api/repository/StoreRepository.java
  src/main/java/com/kosa/mini/api/security/SecurityConfig.java
  src/main/java/com/kosa/mini/api/service/member/FindApiService.java
  src/main/java/com/kosa/mini/api/service/member/FindApiServiceImpl.java
  src/main/java/com/kosa/mini/api/service/member/SuggestionService.java
  src/main/java/com/kosa/mini/api/service/member/SuggestionServiceImpl.java
  src/main/java/com/kosa/mini/api/service/store/StoreApiService.java
  src/main/java/com/kosa/mini/api/service/store/StoreApiServiceImpl.java
  src/main/java/com/kosa/mini/mvc/controller/admin/AdminExController.java
  src/test/java/com/kosa/mini/api/service/member/FindApiServiceImplTest.java
Labels: enhancement

#88 Refactor: 리뷰와 답글 수정 rest 전환
  src/main/java/com/kosa/mini/api/controller/review/ReviewsReplyApiController.java
  src/main/java/com/kosa/mini/api/dto/home/HomeStoreDTO.java
  src/main/java/com/kosa/mini/api/dto/review/ReplyUpdateDTO.java
  src/main/java/com/kosa/mini/api/dto/review/ReviewsUpdateDTO.java
  src/main/java/com/kosa/mini/api/entity/ReviewReply.java
  src/main/java/com/kosa/mini/api/repository/ReviewRepository.java
  src/main/java/com/kosa/mini/api/repository/StoreRepository.java
  src/main/java/com/kosa/mini/api/service/review/ReplyApiService.java
  src/main/java/com/kosa/mini/api/service/review/ReplyApiServiceImpl.java
  src/main/java/com/kosa/mini/api/service/review/ReviewApiService.java
  src/main/java/com/kosa/mini/api/service/review/ReviewApiServiceImpl.java
Labels: refactor

#89 feat: Refresh Token Redis 추가
  build.gradle
  src/main/java/com/kosa/mini/api/config/RedisConfig.java
  src/main/java/com/kosa/mini/api/controller/member/LoginApiController.java
  src/main/java/com/kosa/mini/api/entity/RefreshToken.java
  src/main/java/com/kosa/mini/api/entity/RefreshTokenRedis.java
  src/main/java/com/kosa/mini/api/repository/RefreshTokenRepository.java
  src/main/java/com/kosa/mini/api/security/SecurityConfig.java
  src/main/java/com/kosa/mini/api/service/member/LoginServiceImpl.java
  src/main/resources/application.properties
Labels: enhancement

#93 feat: Add Admin Create Store Feature
  src/main/java/com/kosa/mini/api/controller/admin/AdminApiController.java
  src/main/java/com/kosa/mini/api/dto/store/MenuUploadDTO.java
  src/main/java/com/kosa/mini/api/dto/store/StoreContentDTO.java
  src/main/java/com/kosa/mini/api/dto/store/StoreDTO.java
  src/main/java/com/kosa/mini/api/entity/Menu.java
  src/main/java/com/kosa/mini/api/entity/Role.java
  src/main/java/com/kosa/mini/api/entity/Store.java
  src/main/java/com/kosa/mini/api/exception/FileStorageException.java
  src/main/java/com/kosa/mini/api/exception/GlobalExceptionHandler.java
  src/main/java/com/kosa/mini/api/repository/CategoryRepository.java
  src/main/java/com/kosa/mini/api/repository/StoreRepository.java
  src/main/java/com/kosa/mini/api/service/file/FileStorageService.java
  src/main/java/com/kosa/mini/api/service/file/FileStorageServiceImpl.java
  src/main/java/com/kosa/mini/api/service/store/StoreApiService.java
  src/main/java/com/kosa/mini/api/service/store/StoreApiServiceImpl.java
  src/main/resources/application.properties
Labels: enhancement

#94 Refactor: reviews와 reply 관련 기능 rest 전환
  src/main/java/com/kosa/mini/api/controller/review/ReviewsReplyApiController.java
  src/main/java/com/kosa/mini/api/controller/search/SearchApiController.java
  src/main/java/com/kosa/mini/api/dto/review/StoreReviewDTO.java
  src/main/java/com/kosa/mini/api/dto/search/SearchDTO.java
  src/main/java/com/kosa/mini/api/dto/search/SearchResultDTO.java
  src/main/java/com/kosa/mini/api/dto/search/SearchReviewInterfaceDTO.java
  src/main/java/com/kosa/mini/api/dto/search/SearchReviewResultDTO.java
  src/main/java/com/kosa/mini/api/dto/search/SearchStoreDTO.java
  src/main/java/com/kosa/mini/api/dto/search/SearchStoreInterfaceDTO.java
  src/main/java/com/kosa/mini/api/dto/search/SearchStoreResultDTO.java
  src/main/java/com/kosa/mini/api/entity/Store.java
  src/main/java/com/kosa/mini/api/repository/ReviewRepository.java
  src/main/java/com/kosa/mini/api/repository/StoreRepository.java
  src/main/java/com/kosa/mini/api/service/search/SearchApiService.java
  src/main/java/com/kosa/mini/api/service/search/SearchApiServiceImpl.java
Labels: enhancement, refactor

#95 feat: 비밀번호 인코딩 기능 추가(회원 정보 수정, 닉네임 중복확인 완료)
  src/main/java/com/kosa/mini/api/controller/member/EditProfileApiController.java
  src/main/java/com/kosa/mini/api/dto/member/MemberEditProfileDTO.java
  src/main/java/com/kosa/mini/api/service/member/MemberEditProfileServiceImpl.java
Labels: enhancement

#96 chore: front 셋팅
  frontend/.env
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/stores/auth.js
  frontend/src/views/Login.vue
  src/main/java/com/kosa/mini/api/controller/member/LoginApiController.java
  src/main/java/com/kosa/mini/api/dto/member/AccessTokenDTO.java
  src/main/java/com/kosa/mini/api/dto/member/MemberInfoDTO.java
  src/main/java/com/kosa/mini/api/entity/Member.java
  src/main/java/com/kosa/mini/api/security/SecurityConfig.java
  src/main/java/com/kosa/mini/api/service/member/LoginService.java
  src/main/java/com/kosa/mini/api/service/member/LoginServiceImpl.java
  src/main/java/com/kosa/mini/api/service/member/SignUpServiceImpl.java
Labels: enhancement

#97 feat: 메뉴 이미지 저장 시 DB에 기존 이미지가 있을 경우 삭제 후 저장
  src/main/java/com/kosa/mini/api/controller/admin/AdminApiController.java
  src/main/java/com/kosa/mini/api/dto/store/MenuAdminDTO.java
  src/main/java/com/kosa/mini/api/dto/store/MenuUploadDTO.java
  src/main/java/com/kosa/mini/api/dto/store/StoreCreateDTO.java
  src/main/java/com/kosa/mini/api/entity/Menu.java
  src/main/java/com/kosa/mini/api/repository/MenuRepository.java
  src/main/java/com/kosa/mini/api/repository/StoreRepository.java
  src/main/java/com/kosa/mini/api/service/file/FileStorageService.java
  src/main/java/com/kosa/mini/api/service/file/FileStorageServiceImpl.java
  src/main/java/com/kosa/mini/api/service/menu/MenuApiService.java
  src/main/java/com/kosa/mini/api/service/menu/MenuApiServiceImpl.java
  src/main/java/com/kosa/mini/api/service/store/StoreApiService.java
  src/main/java/com/kosa/mini/api/service/store/StoreApiServiceImpl.java
Labels: enhancement

#98 feat: frontend header 로그인 유지, 회원 제안, 내 정보 수정 추가
  frontend/src/axios.js
  frontend/src/components/Header.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/stores/admin.js
  frontend/src/stores/auth.js
  frontend/src/views/EditProfile.vue
  frontend/src/views/Suggestion.vue
  frontend/src/views/admin/AdminSuggestionList.vue
  frontend/src/views/admin/AdminSuggestionView.vue
  src/main/java/com/kosa/mini/api/controller/member/EditProfileApiController.java
  src/main/java/com/kosa/mini/api/controller/member/LoginApiController.java
Labels: bug, enhancement

#103 feat: 고객 요청 사항, email 찾기(frontend)
  frontend/src/router/index.js
  frontend/src/stores/admin.js
  frontend/src/views/FindEmail.vue
  frontend/src/views/admin/AdminSuggestionList.vue
  frontend/src/views/admin/AdminSuggestionView.vue
  frontend/vite.config.js
Labels: bug, documentation

#104 feat: 회원가입, 내정보수정 frontend 추가
  frontend/src/views/ResetPassword.vue
  frontend/src/views/Signup.vue
  src/main/java/com/kosa/mini/api/controller/member/FindApiController.java
  src/main/java/com/kosa/mini/api/dto/member/FindMemberRequest.java
  src/main/java/com/kosa/mini/api/service/member/FindApiService.java
  src/main/java/com/kosa/mini/api/service/member/FindApiServiceImpl.java
Labels: documentation

#105 feat: 사장 등록 frontend
  frontend/src/router/index.js
  frontend/src/stores/auth.js
  frontend/src/views/admin/RegisterOwner.vue
  src/main/java/com/kosa/mini/api/controller/admin/AdminApiController.java
Labels: enhancement

#108 feat: frontend 가게 등록 및 메뉴 등록
  frontend/.env
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/router/index.js
  frontend/src/stores/admin.js
  frontend/src/views/admin/StoreMenu.vue
  frontend/src/views/admin/StoreRegister.vue
Labels: bug, documentation

#110 feat: 검색 Header, 검색 결과, 에러 page(frontend)
  frontend/src/App.vue
  frontend/src/components/Header.vue
  frontend/src/router/index.js
  frontend/src/stores/admin.js
  frontend/src/views/AccessDenied.vue
  frontend/src/views/Search copy 2.vue
  frontend/src/views/Search copy.vue
  frontend/src/views/Search.vue
  frontend/src/views/admin/StoreRegister.vue
  src/main/java/com/kosa/mini/api/controller/search/SearchApiController.java
  src/main/java/com/kosa/mini/api/service/search/SearchApiService.java
  src/main/java/com/kosa/mini/api/service/search/SearchApiServiceImpl.java
Labels: bug, documentation

#112 feat: frontend search page
  frontend/src/views/Search.vue
  src/main/java/com/kosa/mini/api/controller/search/SearchApiController.java
  src/main/java/com/kosa/mini/api/dto/search/SearchStoreDTO.java
  src/main/java/com/kosa/mini/api/dto/search/SearchStoreInterfaceDTO.java
  src/main/java/com/kosa/mini/api/repository/ReviewRepository.java
  src/main/java/com/kosa/mini/api/repository/StoreRepository.java
  src/main/java/com/kosa/mini/api/security/SecurityConfig.java
  src/main/java/com/kosa/mini/api/security/WebConfig.java
  src/main/java/com/kosa/mini/api/service/search/SearchApiServiceImpl.java
  src/main/resources/application.properties
Labels: enhancement

#113 fix: signup 오류 해결
  src/main/java/com/kosa/mini/api/service/member/SignUpServiceImpl.java
Labels: bug

#115 feat: vue 가게명 추가, 작성자 추가
  frontend/src/views/admin/AdminSuggestionList.vue
  frontend/src/views/admin/AdminSuggestionView.vue
  src/main/java/com/kosa/mini/api/controller/admin/AdminApiController.java
  src/main/java/com/kosa/mini/api/dto/admin/SuggestionDetailDTO.java
  src/main/java/com/kosa/mini/api/repository/SuggestionRepository.java
  src/main/java/com/kosa/mini/api/service/member/MemberEditProfileServiceImpl.java
  src/main/java/com/kosa/mini/api/service/member/SuggestionService.java
  src/main/java/com/kosa/mini/api/service/member/SuggestionServiceImpl.java
Labels: enhancement

#119 feat: frontend home image 불러오기, 내 정보 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/views/EditProfile.vue
  frontend/src/views/Home.vue
  src/main/java/com/kosa/mini/api/controller/member/EditProfileApiController.java
  src/main/java/com/kosa/mini/api/dto/member/MemberEditProfileDTO.java
  src/main/java/com/kosa/mini/api/security/SecurityConfig.java
  src/main/java/com/kosa/mini/api/service/member/MemberEditProfileServiceImpl.java
Labels: bug, enhancement

#121 feat: 가게 상세 페이지 이미지 로드
  frontend/src/views/StoreContent.vue
Labels: enhancement

#123 fix: 가게 등록 로직 오류 수정
  frontend/src/App.vue
  frontend/src/main.js
  frontend/src/views/Home.vue
  src/main/java/com/kosa/mini/api/service/store/StoreApiServiceImpl.java
Labels: enhancement

#125 docs: 기존 "로그인 창에서 회원정보가 존재하지 않습니다." 라는 문구로 수정 완료
  src/main/java/com/kosa/mini/api/controller/member/LoginApiController.java
Labels: fix

#124 fix: Header search 및 dropdown 수정
  frontend/src/components/Header.vue
  src/main/java/com/kosa/mini/api/security/SecurityConfig.java
Labels: fix

#126 fix: vue 헤더 Active Link 스타일 조정 코드 삭제
  frontend/src/components/Header.vue
Labels: fix

#127 fix: search login 요구
  frontend/src/views/Search.vue
Labels: fix

#128 feat: 댓글 modal 생성 성공, css 수정 중
  frontend/src/assets/css/content.css
  frontend/src/views/StoreContent.vue
Labels: fix

#129 feat: 가게 생성(관리자)
  frontend/src/components/MenuRegister.vue
  frontend/src/router/index.js
  frontend/src/stores/admin.js
  frontend/src/views/admin/StoreMenu.vue
  frontend/src/views/admin/StoreRegister.vue
  src/main/java/com/kosa/mini/api/service/menu/MenuApiServiceImpl.java
Labels: enhancement

#130 fix: 메뉴 등록 이슈 수정
  frontend/src/components/MenuRegister.vue
Labels: fix

#132 feat: 가게 수정 추가(frontend), 메뉴는 추가만, 수정은 안됨
  frontend/src/components/MenuRegister.vue
  frontend/src/router/index.js
  frontend/src/stores/admin.js
  frontend/src/views/StoreContent.vue
  frontend/src/views/admin/StoreModify.vue
  frontend/src/views/admin/StoreRegister.vue
  src/main/java/com/kosa/mini/api/service/menu/MenuApiServiceImpl.java
  src/main/java/com/kosa/mini/api/service/store/StoreApiServiceImpl.java
Labels: enhancement, fix

#133 feat: 댓글 수정 기능 구현
  frontend/src/assets/css/content.css
  frontend/src/views/StoreContent.vue
  src/main/java/com/kosa/mini/api/security/SecurityConfig.java
Labels: enhancement, fix

#134 fix: 가게 상세 평점 반올림, 카테고리 추가
  frontend/src/views/StoreContent.vue
  src/main/java/com/kosa/mini/api/controller/store/StoreContentApiController.java
  src/main/java/com/kosa/mini/api/dto/store/StoreContentCategoryDTO.java
  src/main/java/com/kosa/mini/api/service/store/StoreApiService.java
  src/main/java/com/kosa/mini/api/service/store/StoreApiServiceImpl.java
Labels: enhancement, fix

#138 fix: 가게 사진 수정 기능
  frontend/src/stores/admin.js
  src/main/java/com/kosa/mini/api/controller/admin/AdminApiController.java
  src/main/java/com/kosa/mini/api/service/menu/MenuApiServiceImpl.java
Labels: fix

#139 feat: 댓글, 대댓글 모달로 생성, 수정 가능 및 별점 0으로 초기화 되는 에러 수정
  frontend/src/assets/css/content.css
  frontend/src/views/StoreContent.vue
Labels: enhancement, fix

#141 fix: 리뷰 수정 시 메세지 안뜨는 오류 수정
  frontend/src/views/StoreContent.vue
Labels: enhancement, fix

#142 docs: update README.md
  README.md
Labels: documentation
